services:
  dbdevelopment:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/bitnami/postgresql
    container_name: dbdevelopment

volumes:
  postgres_data:
    driver: local



