export type ProductData = {
  id: number;
  layanan: string;
  provider: string;
  providerId: string;
  kategoriId: number;
  catatan: string;
  status: boolean;
  hargaFromDigi: number;
  harga: number;
  hargaSuggest: number;
  hargaPlatinum: number;
  hargaReseller: number;
  profit: number;
  profitSuggest: number;
  profitPlatinum: number;
  profitReseller: number;
  productLogo: string | null;
  isSuggest: boolean;
  isFlashSale: boolean;
  isProfitFixed: boolean;
  judulFlashSale: string | null;
  bannerFlashSale: string | null;
  expiredFlashSale: string | null;
  hargaFlashSale: number | null;
  createdAt: string | null;
  updatedAt: string | null;
};
